# Disable the creation of npm's package-lock.json
enableGlobalCache: true

# Specify the registry to be used by Yarn
npmRegistryServer: "https://registry.yarnpkg.com"

# Ensure Yarn uses its own lockfile
useLockfile: true