export enum Permissions {
    ALL = "ALL",
    CREATE_ADMIN = "CREATE ADMIN", 
    DELETE_ADMIN= "DELETE ADMIN",
    EDIT_ADMIN = "EDIT ADMIN",
    CREATE_CLIENT= "CREATE CLIENT",
    DELETE_CLIENT= "DELETE CLIENT",
    EDIT_CLIENT= "EDIT CLIENT",
    CREATE_SERVICE= "CREATE SERVICE",
    DELETE_SERVICE= "DELETE SERVICE",
    UPDATE_SERVICE= "UPDATE SERVICE",
    DISABLE_SERVICE= "DISABLE SERVICE",
}