export enum Permissions {
    ALL = "ALL", // only super admins
    CREATE_ADMIN = "CREATE ADMIN", 
    DELETE_ADMIN= "DELETE ADMIN",
    EDIT_ADMIN = "EDIT ADMIN",
    CREATE_CLIENT= "CREATE CLIENT",
    DELETE_CLIENT= "DELETE CLIENT",
    EDIT_CLIENT= "EDIT CLIENT",
    CREATE_SERVICE= "CREATE SERVICE",
    DELETE_SERVICE= "DELETE SERVICE",
    UPDATE_SERVICE= "UPDATE SERVICE",
    DISABLE_SERVICE= "DISABLE SERVICE",
    VIEW_CLIENT= "VIEW CLIENT",
    VIEW_ADMIN = "VIEW ADMIN",
    CREATE_BUSINESS= "CREATE BUSINESS",
    EDIT_BUSINESS= "EDIT BUSINESS",
    DELETE_BUSINESS= "DELETE BUSINESS",
}
